# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitstatus" do
  version "1.8.1"

  on_macos do
    on_intel do
      sha256 "e3b1f2db36daffae24d6222af86899f1b708ec4f8bfe80503cbedb252b948dd7"
      url "https://github.com/Jleagle/gitstatus/releases/download/v#{version}/gitstatus_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3d464a363507973d10da6f641f9cd95f3617c95dce21b453621f1382b383aa93"
      url "https://github.com/Jleagle/gitstatus/releases/download/v#{version}/gitstatus_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "77fb1b5be6c62dbcb449035e9b9b2f2d5c174e7e77e37c281ef0fe6abd6d619e"
      url "https://github.com/Jleagle/gitstatus/releases/download/v#{version}/gitstatus_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bfbe25e121b87780fa05854d1de88149d5219d2371bb26333799fc1666722926"
      url "https://github.com/Jleagle/gitstatus/releases/download/v#{version}/gitstatus_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gitstatus"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitstatus"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitstatus"]
    end
  end

  # No zap stanza required

end
