# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitstatus" do
  version "1.8.0"

  on_macos do
    on_intel do
      sha256 "a149d52cb78e307ec2173dec72087f2de7a3a4ce19a14964656b13bbf395d67d"
      url "https://github.com/Jleagle/gitstatus/releases/download/v#{version}/gitstatus_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3d091617d7c0fc6fde0639ee966e57f6d8ac2bfe2c0b26bb81774fe108cfe293"
      url "https://github.com/Jleagle/gitstatus/releases/download/v#{version}/gitstatus_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4a72f91dd490e6d9bdf9ccc1f5550dd3a6c02da4982be895c9736d3c2d08fe0a"
      url "https://github.com/Jleagle/gitstatus/releases/download/v#{version}/gitstatus_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3933141a323895a5b70c4c6d15b0904073a1dd1444b7d5ab9617094807cb410b"
      url "https://github.com/Jleagle/gitstatus/releases/download/v#{version}/gitstatus_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gitstatus"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitstatus"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitstatus"]
    end
  end

  # No zap stanza required

end
