# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitstatus" do
  name "gitstatus"
  desc ""
  homepage ""
  version "1.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitstatus"

  on_macos do
    on_intel do
      url "https://github.com/Jleagle/gitstatus/releases/download/v#{version}/gitstatus_#{version}_darwin_amd64.tar.gz"
      sha256 "389cc3db3d41ebe41974116e1080b17215140862c1e97ac850197d98e9badf82"
    end
    on_arm do
      url "https://github.com/Jleagle/gitstatus/releases/download/v#{version}/gitstatus_#{version}_darwin_arm64.tar.gz"
      sha256 "fed48220a8bcfc374d00f4f5f233ac7d8e9ec98021306fd28579e61eb7ce0ba4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Jleagle/gitstatus/releases/download/v#{version}/gitstatus_#{version}_linux_amd64.tar.gz"
      sha256 "dff61cbb5d97c14d89092ac1204ee187c5c75e000484893232483e7eaca1afde"
    end
    on_arm do
      url "https://github.com/Jleagle/gitstatus/releases/download/v#{version}/gitstatus_#{version}_linux_arm64.tar.gz"
      sha256 "57f7cb4ff24e9e96d28756b984ff98edece4b7bc8cfef5a7a15a6f2cb6ee1276"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitstatus"]
    end
  end

  # No zap stanza required
end
