# Generated by homebrew/formula.sh in Jleagle/gitstatus on each release. DO NOT EDIT.
class Gitstatus < Formula
  desc "Status of every git repo under a directory, with optional pulls"
  homepage "https://github.com/Jleagle/gitstatus"
  url "https://github.com/Jleagle/gitstatus/archive/refs/tags/v2.4.0.tar.gz"
  sha256 "0d9434d7c42ffb73b31f31bcdc6ff88eb327bcebcd85ebb24a4327cc1d7fcf22"
  license "MIT"

  livecheck do
    skip "Updated by the release workflow."
  end

  depends_on "go" => :build

  def install
    # The same -X values the goreleaser builds had; std_go_args adds -s -w.
    ldflags = %W[
      -X main.version=#{version}
      -X main.commit=c3328a8453dfddd42f7f75201d589b2fbb6d20f6
      -X main.date=2026-10-08T18:27:19Z
    ]
    system "go", "build", *std_go_args(ldflags:)
  end

  test do
    assert_match "Version: #{version}", shell_output("#{bin}/gitstatus --version 2>&1")
  end
end
